travis:
  secure:
    BINSTAR_TOKEN: bvZUKBvt7zhzMWCsg7QjEfN8Ey1bH+sYlI7jq9Z3C0DB81D3TqTcKU29DU7h1e4oWhqYv5GL5jtdC5IRqOHfWq/opSbJ8kSRWVQvjAX6YwyyJYbvf3ubAKy0AJ7ZQ8Npa7jTAPQv53ZcKgjwdHA2NISWddaPB3RBqLqnoDx+ywbWO2TtN1UoFlx5Vc9pBLXWKybOechCZ4LhAzUV0YBMgXcTRlnlJcmLJFojpHItgupWULZh4hDQ5ajpfGm/6fDjvGTb39Nkt4o/oC1UJu7dKhPGWxZbr09RlTafG4GlYtJtJYkdRLNLH0laIU5TzJ6ETyB5QQa8KKuWxVJdq/m3GzcFnfR3tev8xWBn0SbHuOTee0w8yNwWSpTsMGwa8pejhiMN0YjLU9CUXJQbd5xF59jdYmx+kJUM+tIVP4oXfDNlwllUP0nZXhFIFPrKcUImiiCmPj+/1VLD6Vlyr9iNOjhhss0kGAfiyVlfXl20PuEW0uWcxk68vPrK031k/6Gc8o356yXPGCKDydkz4gxzGZGyqlg0TQ3k+MlmS140aXbFHVEoTKgaKb03WbwC4dvGtuip7sHClG+EUmv71tHYSuTDVaVrt14Khelo33ywLmRd9d3xmPDAWiKDavNS1IMCQJDGbmxDZOOTO2vS8rYwmBWD0DA3vpOau9RCYGuEkUg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
