travis:
  secure:
    BINSTAR_TOKEN: lFS32F9HLSX1UE2gnmWT/rjgJGL1BiYYZ59TVBNwxJi8xAjqbGb54P1Gd3c2JB4tPgoaMw3mZ6PXS5ihidtlOB5y/fuZ6dCgurcSUWuhxp+EW+9wPYe2gKQcN/mWtxD76td8fS0asWWRo1LQrEoZhSnqpXk5+uMVHc6KMG0Xqw2ZvOqSoGxE8SlibFyecgVkbZpjaqC8U2TD+nPwnOaxF67PLRz2t/vJvQ0u8pVjKhwcd/urRA8oaWDNpfzjFItHjS39m60cDI3qnR2DHR4oi+pkqpkhQ5RQniR7ETfgqr/u7+vR2CcsL/qlm9GkeegFRizp4b3Yil5pHNKPRqqpbWp/gChbr+NPKfFzUsPDvndjgL++WR7OSF63xBT9SlXl5gjcobpflnAwRfFJWh9cJEX+8dPtnfH2q8gwpZmuOTUMDFPlYA1DNbuZkh00dPYYbHOCzmwgS3XFQJ3EB4XMICX7kEPNakU2GG5u0PRqsfFKLGDo27MyOgn6h1SUMONh5q7l9TJenm4H3u+eK7Nkq1fDzRO9CmgV0vi2EV3y0AzARYNNzDkwOnHDHX8eUjBQfQRgCsFojMcweFKRLfzRvN3vcEIFu4vdO8yAF/bFlwm6Zz/id+be0X6EvQUbxop5Vd2LnUU9U3z0P0SBMv+LYZ08KH137aqTdULdsxC182M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
